matrix:
  include:
    - language: java
      before_install:
       - chmod +x scripts/simianServer.bat
      before_script: 
       - cd server
      script: 
       - mvn clean test
       - mvn javadoc:javadoc
      after_script:
       - cd ..
      before_script: 
       - cd scripts
      script: 
       - ./simianServer.bat
      after_script:
       - cd ..
    - language: csharp
      before_install:
       - chmod +x scripts/simianClient.bat
      before_script:
       - cd scripts
      script:
       - ./clientBuild.sh
      after_script:
       - cd ..
      before_script: 
       - cd scripts
      script: 
       - ./simianClient.bat
      after_script:
       - cd ..
