matrix:
  include:
    - language: java
      before_script: 
       - cd server
      script: 
       - mvn clean test
       - mvn javadoc:javadoc
      after_script:
        - cd ..
    - language: csharp
      before_script:
       - cd scripts
      script:
       - ./clientBuild.sh
      after_script:
       - cd ..
