matrix:
  include:
    - language: java
      before_install:
    - chmod +x scripts/serverStart.bat
      before_script:
        - cd scripts
      script:
        - ./serverStart.bat
      after_script:
        - cd ..

    - language: csharp
      before_install:
        - chmod +x scripts/clientBuild.sh
      before_script:
        - cd scripts
      script:
        - ./clientBuild.sh
      after_script:
        - cd ..
