matrix:
  include:
    - language: java
      before_script: 
       - cd server
      script: 
       - mvn clean test
       - mvn javadoc:javadoc
      after_script:
       - cd ..
      before_script: 
       - cd scripts/simian
      script: 
       - ./simian-2.5.10.exe -failOnDuplication + ../../server/src/main/java/com/gameofelte/**/*.java
      after_script:
       - cd ../..
    - language: csharp
      before_script:
       - cd scripts
      script:
       - ./clientBuild.sh
      after_script:
       - cd ..
      before_script: 
       - cd scripts/simian
      script: 
       - ./simian-2.5.10.exe -failOnDuplication + ../../client/**/*.cs
      after_script:
       - cd ..
