matrix:
  include:
    - language: java
      before_install:
       - chmod +x scripts/simian/simian.jar
      before_script: 
       - cd server
      script: 
       - mvn clean test
       - mvn javadoc:javadoc
      after_script:
       - cd ..
      before_script: 
       - cd scripts/simian
      script: 
       - ./java -jar simian.jar -failOnDuplication + ../../server/src/main/java/com/gameofelte/**/*.java
      after_script:
       - cd ../..
    - language: csharp
      before_install:
       - chmod +x scripts/simian/simian.jar
      before_script:
       - cd scripts
      script:
       - ./clientBuild.sh
      after_script:
       - cd ..
      before_script: 
       - cd scripts/simian
      script: 
       - ./java -jar simian.jar -failOnDuplication + ../../client/**/*.cs
      after_script:
       - cd ../..
